- Pod/Classes/URBNMacros.h
- URBNConvenience.podspec
- Created some macros needed for FreePeople to detect if a device is iPhone 6, 6 Plus, or  retina 3x device
> iPhone 6 macros

- Example/URBNConvenience/URBNViewController.m
- Pod/Classes/UIView+URBNLayout.h
- Pod/Classes/UIView+URBNLayout.m
- Pod/Classes/URBNMacros.h
- URBNConvenience.podspec
This adds some extra layout methods to the UIView+URBNLayout category.
> Layout additions

- Example/Podfile.lock
- Example/Pods/Headers/Public/URBNConvenience/UIImage+ImageEffects.h
- Example/Pods/Local Podspecs/URBNConvenience.podspec
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/Pods/Target Support Files/Pods-Tests/Pods-Tests-environment.h
- Example/Pods/Target Support Files/Pods-Tests/Pods-Tests-resources.sh
- Example/Pods/Target Support Files/Pods-URBNConvenience/Pods-URBNConvenience-environment.h
- Example/Pods/Target Support Files/Pods-URBNConvenience/Pods-URBNConvenience-resources.sh
- Example/URBNConvenience/URBNViewController.m
- Pod/Classes/UIImage+ImageEffects.h
- Pod/Classes/UIImage+ImageEffects.m
- Pod/Classes/UIImage+URBN.h
- Pod/Classes/UIImage+URBN.m
- URBNConvenience.podspec
- Added apple's ImageEffects library for bluring an image
- Also added function to get a screenshot of a view
> Blur effects added via Apple's UIImageEffects class

- Example/Pods/Pods.xcodeproj/project.pbxproj
- Pod/Classes/UIImage+URBN.h
- Pod/Classes/UIImage+URBN.m
- URBNConvenience.podspec
- added urbn_ prefix to screenshot method
- moved ImageEffects to its own group in the project
> Some cleanup

- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/Tests/URBNConvenienceTestCase.m
- Pod/Classes/NSDate+URBN.m
- URBNConvenience.podspec
> fixed bug when determining timeSince given a date

- Example/URBNConvenience/URBNViewController.m
- Pod/Classes/UIView+URBNBorders.h
- Pod/Classes/UIView+URBNBorders.m
instead of setting each right, left, top, bottom border color and size; this one method will set these automatically based on one color and one size
> Convenience Method to Add All Borders

- Pod/Classes/URBNConvenience.h
Any reason to *not* have this in the umbrella?
> Add UIView+URBNBorders to Umbrella

- Example/Podfile.lock
- Example/Pods/Local Podspecs/URBNConvenience.podspec.json
- Example/Pods/Manifest.lock
- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/URBNConvenience.xcodeproj/project.pbxproj
- Example/URBNConvenience/Convenience-Bridging-Header.h
- Example/URBNConvenience/SwiftVC.swift
- Example/URBNConvenience/URBNViewController.m
- Pod/Classes/ConstraintConvenience.swift
- Pod/Classes/LayoutConvenience.swift
- Pod/Classes/SearchableProtocol.swift
- URBNConvenience.podspec
swift convenience methods. can't be put in a release until https://github.com/CocoaPods/CocoaPods/pull/4476 is in a release. till then we can use cocoapods dev off the master branch https://guides.cocoapods.org/using/unreleased-features
> View convenience and searchable protocol

- Example/Pods/Pods.xcodeproj/project.pbxproj
- Pod/Classes/UIColor+URBN.h
- Pod/Classes/UIColor+URBN.m
Added UIColor Category methods used in Anthropology to convert hex string to UIColor
> UIColor+URBN

- Pod/Classes/UIImage+URBN.h
- Pod/Classes/UIImage+URBN.m
Added UIImage category method for tintedImageWithColor used in Anthropology to replace UIImage-Additions pod.
> UIImage+URBN tintedImageWithColor

- Example/Pods/Pods.xcodeproj/project.pbxproj
- Example/URBNConvenience.xcodeproj/project.pbxproj
- Example/URBNConvenience/Base.lproj/Main_iPad.storyboard
- Example/URBNConvenience/Base.lproj/Main_iPhone.storyboard
- Example/URBNConvenience/URBNTableViewHelper.swift
- Example/URBNConvenience/URBNTableViewHelperCell.swift
- Example/URBNConvenience/URBNViewController.m
- Pod/Classes/TableViewHelpers.swift
tableview convenience based on  https://medium.com/@calebd/swift-reusable-cells-31391d2f2906#.owjb1kpk2
> Table view helpers

- .travis.yml
- URBNConvenience.podspec
@urbn/mobileteam anyone can review please
> Now with 100% more support for tvOS

- Example/URBNConvenience/SwiftVC.swift
- Pod/Classes/QRCodeGenerator.swift
move to extensions rather than public funcs - swift style update
> Update qr style

- Example/Podfile.lock
- Example/Pods/Local Podspecs/URBNConvenience.podspec.json
- Example/Pods/Manifest.lock
- Example/URBNConvenience.xcodeproj/project.pbxproj
- Pod/Classes/LayoutConvenience.swift
- depricated old func
- added new variadic function which allows your to supply a list of UIView to be added. You can also pass an array of views
Example
```
view.addSubviewWithNoConstraints(view1)
view.addSubviewWithNoConstraints(view2)
```
can now become
`view.view.addSubviewsWithNoConstraints(view1, view2)`
or if you already have an array built
```
let views = [v1, v2, v3]
view.addSubviewsWithNoConstraints(views)
```
> New convenience method addSubviewsWithNoConstraints, takes multiple views

- Example/Podfile.lock
- Pod/Classes/LayoutConvenience.swift
- PR Changes the argument types to match the underlying NSLayoutConstraint method types
> Activate vfl fix

- Example/Podfile.lock
- Pod/Classes/NSNotificationCenter+URBN.h
- Pod/Classes/NotificationConvenience.swift
Add a Swift 3 friendly version of the Notification Convenience functions
> Added Notification Center Convenience

- Example/Podfile.lock
- Pod/Classes/NotificationConvenience.swift
Adds another convenience method for posting notifications.
> Additional notification convenience method

- Pod/Classes/UIImage+URBN.h
- Pod/Classes/UIImageConvenience.swift
FP just did a refactor on their Style files. We had a lot of UIImage helpers that were in there and this is probably a better place for them. So I moved all of them over here and converted the old ones.
> UIImage Helper converted to swift

- Example/Podfile.lock
- Pod/Classes/LayoutConvenience.swift
- Added convenience to wrapInView with InsetConstraints
- The InsetConstraint struct allow to wrapInView with a non required priority
- Made for use inside collapsable stackViews to avoid layout constraint warnings
> WrapInView w/ Priority

- Pod/Classes/LayoutConvenience.swift
Made InsetConstraint initilizers public
> Layout_Priority Hotfix
